# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 张潇的博客
subtitle: 'Xiao Bro s Blog'
description: 'Happy Developer'
keywords: 'Blog,博客,张潇'
author: Zhang Xiao
language: zh-CN
timezone: ''
use_cdn: true
favicon: https://avatars1.githubusercontent.com/u/11972255?s=460&u=134892f02ec2decebc5a9cd71a8aac26dd032c2e&v=4
baidu_analytics_key: fb53c51dfd71426d827b5f219ce27b79

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.anymelon.com
permalink: :year/:month-:day-:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 20
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: volantis

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

# SEO
sitemap:
  path: sitemap.xml

baidusitemap:
  path: baidusitemap.xml

nofollow:
  enable: true
  exclude:

robotstxt:
  useragent: "*"
  disallow:
  allow:
    - /*
  sitemap: /sitemap.xml

theme_config:
  mermaid: ## mermaid url https://github.com/knsv/mermaid
    enable: true  # default true
    version: "7.1.2" # default v7.1.2
    options:  # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
    startOnload: true  // default true

  meta:
    author:
      name: Xiao Bro
      url: https://张潇.com
      avatar: https://avatars1.githubusercontent.com/u/11972255?s=460&u=134892f02ec2decebc5a9cd71a8aac26dd032c2e&v=4
  cover:
    title: 张潇的博客
    search: 搜索博文
    subtitle: 'A Happy Developer.'
    features:
      - name: 首页
        img: https://blog-file.anymelon.com/assets/1f4f0.svg
        url: /
      - name: 归档
        img: https://blog-file.anymelon.com/assets/1f5c3.svg
        url: /archives/
      - name: 分类
        img: https://blog-file.anymelon.com/assets/1f5c2.svg
        url: /categories/
      - name: 标签
        img: https://blog-file.anymelon.com/assets/1f516.svg
        url: /tags/
      - name: GitHub
        img: https://blog-file.anymelon.com/Octocat2.png
        height: 41px
        url: 'https://github.com/wszxdhr'
      - name: 个人主页
        img: https://blog-file.anymelon.com/assets/1f3aa.svg
        url: 'https://张潇.com'
  style:
    body:
      effect: [shadow,blur]
    sidebar:
      effect: [shadow,blur]
    navbar:
      effect: [shadow,blur]
  navbar:
    logo:
      title: XiaoBro
      version: 'HUB'
      doc: https://blog.anymelon.com
      img:
#      img: https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f516.svg
    visiable: always # always, auto
    menu:
      - name: 首页
        icon: fas fa-home
        url: /
      - name: 归档
        icon: fas fa-book
        url: /archives/
      - name: 分类
        icon: fas fa-list
        url: /categories/
      - name: 标签
        icon: fas fa-flag
        url: /tags/
      - name: Github
        icon: fab fa-github
        url: 'https://github.com/wszxdhr'
      - name: 关于博主
        icon: fas fa-ellipsis-v
        rows:
          - name: 关于博主
            url: /about
          - name: 个人主页
            url: https://张潇.com
          - name: 个人简历
            url: https://张潇.com/张潇的简历.pdf
          - name: 联系博主
            url: mailto:job@anymelon.com
      - name: 暗黑模式 # 可自定义
        icon: fas fa-moon # 可自定义
        toggle: darkmode

    search: 搜索

  plugins:
    aplayer:
      enable: false
    backstretch:
      enable: true
      js: https://blog-file.anymelon.com/assets/jquery.backstretch.min.js
      position: fixed       # cover: sticky on the cover.   fixed: Fixed as background for the site.
      duration: 20000       # Duration (ms)
      fade: 1500            # fade duration (ms) (Not more than 1500)
      images:               # For personal use only. At your own risk if used for commercial purposes !!!
        - https://blog-file.anymelon.com/assets/001.jpg
        - https://blog-file.anymelon.com/assets/002.jpg
        - https://blog-file.anymelon.com/assets/003.jpg
        - https://blog-file.anymelon.com/assets/004.jpg
        - https://blog-file.anymelon.com/assets/005.jpg
        - https://blog-file.anymelon.com/assets/006.jpg
        - https://blog-file.anymelon.com/assets/012.jpg
        - https://blog-file.anymelon.com/assets/016.jpg
        - https://blog-file.anymelon.com/assets/019.jpg
        - https://blog-file.anymelon.com/assets/025.jpg
        - https://blog-file.anymelon.com/assets/033.jpg
        - https://blog-file.anymelon.com/assets/034.jpg
        - https://blog-file.anymelon.com/assets/035.jpg
        - https://blog-file.anymelon.com/assets/038.jpg
        - https://blog-file.anymelon.com/assets/039.jpg
        - https://blog-file.anymelon.com/assets/042.jpg
        - https://blog-file.anymelon.com/assets/046.jpg
        - https://blog-file.anymelon.com/assets/051.jpg
        - https://blog-file.anymelon.com/assets/052.jpg
        - https://blog-file.anymelon.com/assets/054.jpg
        - https://blog-file.anymelon.com/assets/056.jpg

  search:
    enable: true
    service: hexo
  comments:
    title: <i class='fas fa-comments'></i> 评论
    subtitle: 欢迎提问或提出宝贵意见，博主会在看到的第一时间回复~
    service: gitalk # valine, disqus, gitalk, livere
    valine: false
    gitalk:
      clientID: f02555703ef89d86700d
      clientSecret: 67a91ccc471e85a0267088168d6877687553d752
      repo: 'myDaily'
      owner: 'wszxdhr'
      admin: ['wszxdhr']


import:
  link:
  script:
    - '<style type="text/css"> .cover-body .navigation a img { width: 40px; height: 40px; } .cover-body .navigation a p { word-break: keep-all; } </style>'
    - '<style type="text/css">.md .footer .related_posts .body .vlts-rps .item { text-align: center; } .md .footer .related_posts .body .vlts-rps img { width: auto; height: 200px; }</style>'
    - '<style type="text/css">[data-user-color-scheme=dark] .hljs { background: #1a1a1a; }</style>'
    - '<style type="text/css">[data-user-color-scheme=dark] .mermaid .messageText { fill: #f2f2f2; }</style>'
    - '<style type="text/css">[data-user-color-scheme=dark] .mermaid #arrowhead { fill: #f2f2f2; }</style>'
    - '<style type="text/css">[data-user-color-scheme=dark] .mermaid .messageLine0 { stroke: #f2f2f2; }</style>'
    - '<style type="text/css">[data-user-color-scheme=dark] .mermaid .actor-line { stroke: #e7e7e7; }</style>'
    - '<style type="text/css">[data-user-color-scheme=dark] .hljs-comment { color: #ccc; }</style>'
    - '<style type="text/css">[data-user-color-scheme=dark] .hljs { color: #ccc; }</style>'
    - '<style type="text/css">.article pre { border-color: #e7e7e7; }</style>'
    - '<style type="text/css">.about-github-show { margin: 0 auto; }</style>'
    - '<style type="text/css">.cover-wrapper .cover-body .title, .cover-wrapper .cover-body .subtitle { text-shadow: 0 0px 14px rgb(68 68 68 / 50%); }</style>'
    - '<style type="text/css">[data-user-color-scheme=dark] .dark-mode-hide { display: none; }</style>'
    - '<style type="text/css">[data-user-color-scheme=dark] .dark-mode-show { display: block; }</style>'
    - '<style type="text/css">.dark-mode-show { display: none; }</style>'
    - '<script src="https://blog-file.anymelon.com/assets/mermaid.min.js"></script>'
    - '<script>if (window.mermaid) {mermaid.initialize({theme: "forest" });}</script>'
