# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.15]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm ci
      - run: npm run build
      # 发布到服务器
      - name: Install SSH key for deploy
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: "public/"
          REMOTE_HOST: ${{ secrets.SSH_HOST_IP }}
          REMOTE_USER: ${{ secrets.ECS_USER }}
          TARGET: ${{ secrets.ECS_WORKSPACE }}
      # 发布到七牛
      - run: npm run deploy:qiniu -- --ak ${{ secrets.ACCESS_KEY }} --sk ${{ secrets.SECRET_KEY }}
        env:
          CI: true
      # 发布到GitHub Pages
#      - name: Deploy
#        uses: JamesIves/github-pages-deploy-action@releases/v3
#        with:
#          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#          # REPOSITORY_NAME: wszxdhr.github.io
#          BRANCH: gh-pages
#          FOLDER: public
